### ISSUE TITLE
Document the nullability of the EPXProximityRange initializer

### ISSUE THREAD

**Issue by heypiotr** [Estimote/iOS-Proximity-SDK#1]
The `initWithDesiredMeanTriggerDistance` initializer and the `customRangeWithDesiredMeanTriggerDistance` factory method are marked as `nullable`, and it's not immediately obvious why. From talking to @airalex, I learned it's in case somebody passes a negative distance. I believe this behavior is worth an extra line of documentation in the headerdoc (:

**Comment by airalex** [comment]
Fixed in [v0.9.0](https://github.com/Estimote/iOS-Proximity-SDK/releases/tag/v0.9.0) release.
