### ISSUE TITLE
Not called any methods of onEnterAction or onExitAction , onChangeAction

### ISSUE THREAD

**Issue by sw-tt-ravivora** [Estimote/iOS-Proximity-SDK#10]
I am using your latest repository. but not able to get any callback on enterAction or exitAction methods.
Though i have setup all information on estimote cloud to related beacons.

**Comment by megataps** [comment]
@sw-tt-ravivora Did you turn on Bluetooth on your devices?

**Comment by sw-tt-ravivora** [comment]
yes bluetooth is enabled.

**Comment by megataps** [comment]
Did you see your beacons in Estimote app?

**Comment by sw-tt-ravivora** [comment]
yes, even i can able to get list of beacons in previous estimote sdk using didrangebeacons delegate methods.

**Comment by bartlomiejolma** [comment]
Hello @sw-tt-ravivora, @megataps !

@sw-tt-ravivora Have you add attachments to your beacons in Estimote Cloud like described in TODO sections in the demo application? Do you see any logs from an App?
 
Alternatively, can you verify if [Proximity App Template](https://cloud.estimote.com/#/apps/add/proximity-content-single) works for you?

**Comment by sw-tt-ravivora** [comment]
Hi,
    here are screenshots i setup all and app ID , token also of my account.

![screen shot 2018-04-13 at 11 04 23 am](https://user-images.githubusercontent.com/25667759/38718685-e50ad024-3f0b-11e8-8164-cc473c9fc78b.png)
![screen shot 2018-04-13 at 11 13 05 am](https://user-images.githubusercontent.com/25667759/38718686-e5317b34-3f0b-11e8-8afc-c5b4639a0807.png)
![screen shot 2018-04-13 at 11 13 21 am](https://user-images.githubusercontent.com/25667759/38718687-e55b2b64-3f0b-11e8-80b1-7780fc23cf90.png)
![screen shot 2018-04-13 at 11 13 38 am](https://user-images.githubusercontent.com/25667759/38718689-e5a33364-3f0b-11e8-800b-9af39934c09f.png)

**Comment by bartlomiejolma** [comment]
@sw-tt-ravivora from your screenshots I can see that you are using the old version of Proximity Beacons (Hardware Revision D3.4) which does not support Estimote Monitoring (Estimote Location/Estimote Monitoring Tab is not shown on your device settings modal). We are not supporting those beacons in Proximity SDK right now. 

For beacons with Hardware Revision D3.4 you can use old [Estimote iOS SDK](https://github.com/Estimote/iOS-SDK)

**Comment by sw-tt-ravivora** [comment]
Ok , Thanks for giving information.
