### ISSUE TITLE
cocoapods error

### ISSUE THREAD

**Issue by Zedd0202** [Estimote/iOS-Proximity-SDK#11]
**Pods/EstimoteProximitySDK/EstimoteProximitySDK/EstimoteProximitySDK.framework/EstimoteProximitySDK compiled with older version of Swift language (4.0) than previous files (unknown ABI version 0x06)** 

I got this error. any solution?

- I already added my Podfile
platform :ios, '10.0'

**Comment by bartlomiejolma** [comment]
Hello @Zedd0202 

With the latest release (0.12.0) we have updated Proximity SDK to use Swift in version 4.1 which breaks binary-level compatibility with the previous version. 

To solve your issue you can:
- Update your Xcode to the latest version (which will update your Swift version too) - this is a recommended solution
- Explicitly pick from the cocoapods version 0.11.3 build with old Swift.
