### ISSUE TITLE
Xcode 9.3 with EstimoteProximitySDK (0.12.0) error Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)

### ISSUE THREAD

**Issue by n0hkie** [Estimote/iOS-Proximity-SDK#12]
Running but after a while app is crashing 
<img width="1154" alt="screen shot 2018-04-18 at 4 54 31 pm" src="https://user-images.githubusercontent.com/3851075/38921850-4f6adf4c-4329-11e8-800a-49e0e1ea9da9.png">
<img width="497" alt="screen shot 2018-04-18 at 4 56 49 pm" src="https://user-images.githubusercontent.com/3851075/38921933-869237cc-4329-11e8-9efd-52356bac36cf.png">

**Comment by bernayu** [comment]
+1

**Comment by Marlon-Monroy** [comment]
@n0hkie  I'm getting the same crash caused by ` https://github.com/Estimote/iOS-Proximity-SDK/blob/a6a84f820ded5a4211499d0c1fb58dd232a0dca3/EstimoteProximitySDK/EstimoteProximitySDK.framework/PrivateHeaders/EPXTimerAnalyticsHeartbeatGenerator.h `

**Comment by heypiotr** [comment]
I've just run into the same problem, and I believe this happens when your ProximityObserver gets released/deallocated without you calling `stopObservingZones` first.

**Comment by NandhuNair** [comment]
I'm also facing the same issue. Any solution?

**Comment by Marlon-Monroy** [comment]
@NandhuNair  make sure your not calling observe zones one then once, some how in my code i was calling it twice, that fixed the error for me.

**Comment by NandhuNair** [comment]
Thanks @Marlon-Monroy 
Can I call **startObservingZones** again after calling **stopObservingZones** ?

**Comment by Marlon-Monroy** [comment]
@NandhuNair  why would you want to stop it? but yeah I guess you can.

**Comment by chwastek** [comment]
please confirm with https://github.com/Estimote/iOS-Proximity-SDK/releases/tag/v0.13.1 that you don't have this issue
