### ISSUE TITLE
#question: Configure iBeacons

### ISSUE THREAD

**Issue by idelfonsog2** [Estimote/iOS-Proximity-SDK#16]
Does the Estimote iOS app able to configure tags for iBeacons?

**Comment by heypiotr** [comment]
Yes, you can enable iBeacon advertising on Estimote Beacons via the Estimote iOS app.

For the future: this is an issue tracker for the Estimote Proximity SDK. For questions, and anything unrelated to the Proximity SDK, you can use our forums: https://forums.estimote.com, or email us to contact@estimote.com.
