### ISSUE TITLE
SDK(0.14.0) - Fetching tags from Cloud failed

### ISSUE THREAD

**Issue by CloudHN04** [Estimote/iOS-Proximity-SDK#17]
Xcode: 9.4.1
iOS: 11.4

trying to connect to the Cloud services I have my API ID and my AppToken correctly on my code but always getting this problem

EPXProximityObserver error: Error Domain=EPXProximityObserverErrorDomain Code=1 "Fetching tags from Cloud failed." UserInfo={NSUnderlyingError=0x1c4291210 {Error Domain=EstimoteProximitySDK.TagsMappingProvider.Error Code=1 "(null)"}, NSLocalizedDescription=Fetching tags from Cloud failed., NSLocalizedRecoverySuggestion=Make sure your cloud credentials are correct and you have a valid internet connection. See EPXCloudCredentials for more.}

**Comment by chwastek** [comment]
Well, there could be few reasons for that. Did you
- check for sure Internet connection (e.g. proxy is not blocking)?
- assign a tag to any of your devices?
And eventually please tell me what is your account, so I can try to check it up on our side :)

**Comment by CloudHN04** [comment]
Hello @chwastek, 

Yes I checked the internet connection there no blocking on any port or via proxy
I've assigned a tag to the device.

I tested also on the Android SDK I didn't have that kind of problem

**Comment by CloudHN04** [comment]
@chwastek any updates on this?

Thanks

Erick

**Comment by chwastek** [comment]
@CloudHN04 it is still very important remark! 👍 Though happy it is solved :)

**Comment by chwastek** [comment]
@CloudHN04 can you tell me exactly what was this tag, that produced the issue?

**Comment by CloudHN04** [comment]
@chwastek for example words like "caja" or "tres", "seis" seems to have the problem.

**Comment by chwastek** [comment]
@CloudHN04 is it still an issue? these short tags names?
