### ISSUE TITLE
Can't fetch my beacon attachments. 

### ISSUE THREAD

**Issue by karthironald** [Estimote/iOS-Proximity-SDK#18]
Hi, 

I am using 0.14.0 SDK and I can able to add listener for my beacons using **tag**. But in onEnter/onChange completion handler i am not getting attachments inside my context for my beacon. I have properly configured beacon attachment in cloud. **Tag** and **deviceIdentifier** are available in context, only beacon attachments is **nil**. Kindly refer below images. 

Can you please help me to fix it?

<img width="1085" alt="screen shot 2018-06-22 at 2 31 25 pm" src="https://user-images.githubusercontent.com/19427160/41768181-2128e66e-7629-11e8-9e32-50b1258c77b4.png">
<img width="1079" alt="screen shot 2018-06-22 at 2 31 39 pm" src="https://user-images.githubusercontent.com/19427160/41768182-2185816c-7629-11e8-8cb8-01f809b2e876.png">
<img width="326" alt="screen shot 2018-06-22 at 2 41 28 pm" src="https://user-images.githubusercontent.com/19427160/41768720-aa9903ba-762a-11e8-9b36-5a1194da16f6.png">

**Comment by karthironald** [comment]
Hi,

Can I have any update on this please?

**Comment by chwastek** [comment]
@karthironald bug in fetching multiple attachments, added to backlog

**Comment by karthironald** [comment]
When can I expect this to be fixed?

**Comment by chwastek** [comment]
@karthironald I'd expect it to be fixed within next few days

**Comment by karthironald** [comment]
Okay thanks for your information.

**Comment by chwastek** [comment]
@karthironald please check, it should be ok now 😄 with the same SDK version!

**Comment by karthironald** [comment]
Okay 👍. Will check and update you.

**Comment by karthironald** [comment]
Yep 😃, now I'm getting my **beacon attachments** in **context**. Thanks for your work.
