### ISSUE TITLE
Module compiled with Swift 4.1.2 cannot be imported in Swift 4.1.50

### ISSUE THREAD

**Issue by Erik262** [Estimote/iOS-Proximity-SDK#19]
Hello, using Xcode 10 on Mojave 10.14 will couse this error "Module compiled with Swift 4.1.2 cannot be imported in Swift 4.1.50"

- Also when I using the ToolChain Swift 4.1.2
- Changing Swift version in the settings didn't work.

Any Solution to Fix that ?

Thanks!

**Comment by jhkaplan** [comment]
Having same issue. Developing app for iOS 12, getting error "Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler.  Is there any solution to this?

**Comment by Erik262** [comment]
Maybe it could helps you:
Go to https://swift.org/download/ 
Download and install the toolchain for Xcode 9.4. There is a link under "Xcode 9.4" **(Toolchain)**

Then in Xcode choose: Xcode -> Toolchains -> Swift 4.1.2
Now it should work again :)

**Comment by jhkaplan** [comment]
Thanks @Erik262, that did help some, although now I get the error "Command CompileSwift failed with a nonzero exit code" when trying to build with this new toolchain. The error disappears when I revert back to the standard Xcode 10 toolchain.

**Comment by deepeshwp** [comment]
After i revert back to back to the standard Xcode 10 i get back the same error ; Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2

**Comment by hishma** [comment]
+1

**Comment by buechner** [comment]
+1 Swift 4.1.2 ToolChain not helping

**Comment by bprzemyslaw** [comment]
We brought official support for Swift 4.2 now, with [version 1.2.0](http://github.com/Estimote/iOS-Proximity-SDK/releases/tag/v1.2.0).
