### ISSUE TITLE
Estimote Telemetry packet ?

### ISSUE THREAD

**Issue by trietlam** [Estimote/iOS-Proximity-SDK#2]
Hi there,

I'm just wondering if it is recommended to use this iOS-Proximity-SDK for listening to Estimote Telemetry packets  (same as Android-Proximity-SDK) ? Or should we stick to old iOS-SDK ?

**Comment by airalex** [comment]
Hey @trietlam 

iOS Proximity SDK depends on [Estimote Bluetooth Scanning](https://github.com/Estimote/iOS-Bluetooth-Scanning) so the latter one should be available in your project if it's already using Proximity SDK. Keep in mind that at the moment Estimote Bluetooth Scanning framework is not intended as developer-friendly library and thus, it lacks tutorials and examples. Please treat this as a workaround/unofficial solution, as we're still debating how to expose telemetry data in the world where our new Proximity SDK exists. If you don't mind using both Proximity SDK and the iOS SDK (the _old one_) I'd simply follow the [Developer Portal](https://developer.estimote.com/sensors/estimote-telemetry/).

However, if you really want to use plain telemetry packets scanning without iOS SDK (the _old one_), use [Universal Scanner](https://github.com/Estimote/iOS-Bluetooth-Scanning/blob/master/EstimoteBluetoothScanning/EstimoteBluetoothScanning.framework/Headers/EBSUniversalScanner.h) together with [Scan Info Telemetry A](https://github.com/Estimote/iOS-Bluetooth-Scanning/blob/master/EstimoteBluetoothScanning/EstimoteBluetoothScanning.framework/Headers/EBSScanInfoEstimoteTelemetryA.h) and [Scan Info Telemetry B](https://github.com/Estimote/iOS-Bluetooth-Scanning/blob/master/EstimoteBluetoothScanning/EstimoteBluetoothScanning.framework/Headers/EBSScanInfoEstimoteTelemetryB.h). Here's a snippet illustrating how to do it in App Delegate:
```swift
import UIKit
import EstimoteBluetoothScanning

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?
    var universalScanner: EBSUniversalScanner!

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        self.universalScanner = EBSUniversalScanner()
        self.universalScanner.delegate = self
        self.universalScanner.startScanForDevicesRepresented(byClasses: [EBSScanInfoEstimoteTelemetryA.self,
                                                                         EBSScanInfoEstimoteTelemetryB.self])
        
        return true
    }

}

extension AppDelegate: EBSUniversalScannerDelegate {
    
    func universalScanner(_ universalScanner: EBSUniversalScannerProtocol, didScanEstimoteDevice scanInfo: EBSScanInfo) {
        print("Scanned \(scanInfo)")
    }
    
    func universalScanner(_ universalScanner: EBSUniversalScannerProtocol, didFailToScanWithError error: Error) {
        print("Oops! \(error)")
    }
    
}

```

**Comment by trietlam** [comment]
Thanks @airalex  for the clarification.
Cheers !!!
