### ISSUE TITLE
HTTPS requests informations

### ISSUE THREAD

**Issue by Tibb** [Estimote/iOS-Proximity-SDK#20]
Hi,

Could you give us some information/documentation regarding the requests you fire through the Proximity Framework?  

I've counted 10 to 50 GET requests per minute, mainly like this one:
`https://resolver.api.estimote.com/V1/decrypt?ef=abcdefghi01234567`

What's the purpose of these requests? Is there a way to lighten this number?

In general, I was not able to find pre-requisites regarding the recommended network configuration (accesses to open, port, etc).

Thanks a lot for your help!

**Comment by chwastek** [comment]
Hey @Tibb 
sorry for the delay! These requests are needed for Secure Monitoring (both foreground and background) and unfortunately currently they cannot be disabled/tweaked.
Regards

**Comment by Tibb** [comment]
Thanks for the info!
