### ISSUE TITLE
ProximityObserverHandler

### ISSUE THREAD

**Issue by vasquezdennisalon** [Estimote/iOS-Proximity-SDK#21]
How can ProximityObserverHandler be implemented in ios

**Comment by chwastek** [comment]
Please double check [our snippets](
https://github.com/Estimote/iOS-Proximity-SDK#inside-your-app). From your question I assume you're influenced by Android Proximity SDK, right? On iOS there is no _handler_, because handling of enter/exit actions is done on zone's callbacks.
