### ISSUE TITLE
Estimote dont connect to cloud service

### ISSUE THREAD

**Issue by Alexdelgadodiaz** [Estimote/iOS-Proximity-SDK#23]
I have my iBeacon set and I get this error. I am using cocoapods `pod 'EstimoteProximitySDK', '~> 1.0' ` and my beacons have tags, what am I doing wrong? 

> Ooops! Error Domain=EPXProximityObserverErrorDomain Code=1 "Fetching tags from Cloud failed." UserInfo={NSUnderlyingError=0x1c00a83a0 {Error Domain=EstimoteProximitySDK.PersistentTagsRepository.Error Code=2 "When running offline, internet connection is required when starting the observer for the first time."}, NSLocalizedDescription=Fetching tags from Cloud failed., NSLocalizedRecoverySuggestion=Make sure your cloud credentials are correct and you have a valid internet connection. See CloudCredentials for more.}

**Comment by karthironald** [comment]
Did you check internet connection at when you add listener? Because I hope adding listener using tags needs internet connection to get beacons details from estimote cloud.

**Comment by Alexdelgadodiaz** [comment]
Yep, my phone is connected to internet at all times... I tried with 4G and wifi connection. The rest of the app connects correctly to services but this one says that there is no internet connection, it´s weird and this is the reason I am asking here :D

**Comment by chwastek** [comment]
My first guess is that it is mishandling of error and probably no devices are assigned to provided tags. Basically this case could happen when downloading tags from Cloud fails (no devices assigned, requests not coming through) and you have no cached info so far.

1. Are you sure you assigned tags (that you wrapped within `EPXProximityZone`s and added to `EPXProximityObserver`!) to devices?
2. Are you sure your requests are coming back with 200?
3. Can you check up what is exactly under `NSUnderlyingErrorKey` of returned error from `EPXProximityObserver`?

**Comment by chwastek** [comment]
how's it going @Alexdelgadodiaz ? ;)

**Comment by chwastek** [comment]
Hey @Alexdelgadodiaz 
can you confirm if everything is ok?

**Comment by chwastek** [comment]
Closing for long inactivity

**Comment by huynhpeter** [comment]
I have the same error. I'm running the @estimote/react-native-proximity. Then I built the iOS example app and am running it in dev mode on my iphone. I'm seeing the exact error that's described in this ticket. Where do i go to assign the tags? My requests seem to be coming back with status code 200 from what the terminal in VSCode is saying. 

I'm pretty new to react native and beacon tech. Any help would be great! Thanks!
