### ISSUE TITLE
EPXProximityObserver instantiation fails every single time

### ISSUE THREAD

**Issue by marcosjvivar** [Estimote/iOS-Proximity-SDK#24]
We have been using EstimoteProximitySDK since it came out and unfortunately we haven't been able to migrate to the tag-based approach yet, so we have been using the attachment-based approach.

We have implemented a singleton class which handles instantiation and responses from the "onChangeAction" execution block.

We have defined the EPXProximityObserver as follows:
**`private var proximityObserver:EPXProximityObserver!`**

Then, the instantiation of a EPXProximityObserver fails every single time with both methods:

**`self.proximityObserver = EPXProximityObserver(credentials: estimoteCloudCredentials, configuration: EPXProximityObserverConfiguration.default, errorBlock: onError)`**
and
**`self.proximityObserver = EPXProximityObserver(credentials: estimoteCloudCredentials, errorBlock: onError)`**

Is there a way to force the instantiation???

**Comment by chwastek** [comment]
Hey @marcosjvivar 
Which version of SDK do you use? And what you mean exactly by:
>fails every single time

Is there anything that can indicate the source of the issue or at least be helpful in doing so?
You did provide properly credentials `EPXProximityObserver`?

**Comment by chwastek** [comment]
Closing for long inactivity
