### ISSUE TITLE
Can not upload to App Store. “Error Unsupported Architectures EstimoteProcimitySDK.framework”  

### ISSUE THREAD

**Issue by tong9977** [Estimote/iOS-Proximity-SDK#26]
I have a 
![screen shot 2018-08-24 at 15 02 57](https://user-images.githubusercontent.com/5284877/44572818-409dd100-a7af-11e8-9b0b-a26e7bf5bc39.png)
![screen shot 2018-08-24 at 15 02 57](https://user-images.githubusercontent.com/5284877/44572826-47c4df00-a7af-11e8-8103-56e9d939a9af.png)

problem about unloading my app on the App Store. It shows “Error Unsupported Architectures for EstimoteBluetoothScaning.framework” and “EstimoteProcimitySDK.framework” (please find the attached photo)

**Comment by tong9977** [comment]
![screen shot 2018-08-24 at 15 00 49](https://user-images.githubusercontent.com/5284877/44572931-72af3300-a7af-11e8-8dca-cea38bc8a68f.png)

**Comment by heypiotr** [comment]
We do include the simulator architectures in our build of the Proximity SDK. When uploading to the App Store however, Apple requires your to strip those architectures. CocoaPods does this by default, but if you're not using CocoaPods, you can simply add it to your build phase. There's a number of ready-made scripts to do that on the Internet, so you should be able to find something that works for you.
