### ISSUE TITLE
No devices assigned to 'tag name'

### ISSUE THREAD

**Issue by irvingdp** [Estimote/iOS-Proximity-SDK#28]
I have set 6 zones and assign tag name ad range_1, range_3, range_6, range_10, range_15, range_20.
and also set range as 1,3,6,10,15,20 meter by customRangeWithDesiredMeanTriggerDistance.

My estimote cloud account assigned only a beacon and set tag name to  range_6, after I start Observing Zones on iphone 6s, I always saw a log say 'No devices assigned to range_1' and no any onEnter & onExit & onContextChange event triggered. (I expected the event should be triggered, and return the tag range_6) , please help to investigate the issue. thanks.

**Comment by chwastek** [comment]
sorry for closing, accidentally clicked 😅

**Comment by irvingdp** [comment]
finally, I set all tags to a dummy beacon to resolve the problem. thanks.
