### ISSUE TITLE
XCode 10/iOS 12 - dyld: Symbol not found: __T0BOWV

### ISSUE THREAD

**Issue by mdanks** [Estimote/iOS-Proximity-SDK#30]
Hi,

  We just updated to the Released XCode 10 and iOS 12 today.  After compiling and running our app, I get a runtime crash at startup:

```
dyld: Symbol not found: __T0BOWV
Referenced from: /private/var/containers/Bundle/Application/70736500-5A67-4B5D-8D00-31C4C355E6D9/<>.app/Frameworks/EstimoteProximitySDK.framework/EstimoteProximitySDK
  Expected in: /private/var/containers/Bundle/Application/70736500-5A67-4B5D-8D00-31C4C355E6D9/<>.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/70736500-5A67-4B5D-8D00-31C4C355E6D9/<>.app/Frameworks/EstimoteProximitySDK.framework/EstimoteProximitySDK
```

From a quick Google, looks like you may need to release a new version of the library?  We are currently on EstimoteProximitySDK 1.1.0

Thanks!
Mark

**Comment by chwastek** [comment]
Hey @mdanks 
we release this one https://github.com/Estimote/iOS-Proximity-SDK/releases/tag/v1.1.0-swift4.2 about a week ago. Please check with this version and let us know if there are any problems.
Thanks
Filip

**Comment by mdanks** [comment]
Hi @chwastek ,

 I'll take a look, but from the other bug reports, this is a stop gap solution.  Are you planning to update the released version so we don't have to do workarounds?

Thanks!
Mark

**Comment by chwastek** [comment]
@mdanks actually we stumbled upon this issue in the meantime: https://github.com/Estimote/iOS-Proximity-SDK/issues/29 so yes, another release is coming very soon 😉

**Comment by chwastek** [comment]
@mdanks https://github.com/Estimote/iOS-Proximity-SDK/releases/tag/v1.2.0 here you go!

**Comment by leonardoRestrepoIndesap** [comment]
Cocoa pod still being 1.1.0

**Comment by chwastek** [comment]
@leonardoRestrepoIndesap please double check with _current_ version 1.2.0 on Cocoapods (https://cocoapods.org/pods/EstimoteProximitySDK) and confirm if you have any issues

**Comment by leonardoRestrepoIndesap** [comment]
Cocoapods version is 1.2.0 now and is working, thank you so much ;)

**Comment by irvingdp** [comment]
Hi @chwastek ,
We also encountered the same issue, but we are currently on EstimoteProximitySDK 0.13.1, may you also release a version for swift 4.2.  thanks~

**Comment by ShugaSvc** [comment]
hi @@chwastek will we also get a release for 0.13.1?
