### ISSUE TITLE
Code signing "EstimoteBluetoothScanning.framework" failed.

### ISSUE THREAD

**Issue by leonardoRestrepoIndesap** [Estimote/iOS-Proximity-SDK#31]
After add Estimote Proximity SDK manually for IOS 12 this is my problem to upload my project to AppStore

**Comment by chwastek** [comment]
hey @leonardoRestrepoIndesap 
Which version of Proximity SDK do you mean?

**Comment by Syngmaster** [comment]
Hi, getting this error when trying to distribute an archive: 
Failed to verify bitcode in EstimoteBluetoothScanning.framework/EstimoteBluetoothScanning:
error: Cannot extract bundle from /var/folders/h4/h3h2gczd1pg31zfh_swv2l8r0000gn/T/XcodeDistPipeline.QEs/Root/....

The problem occurred once I updated EstimoteProximitySDK and EstimoteBluetoothScanning to the latest versions yesterday. I set enable_bitcode to NO for both the target and the project, but the error still shows up
