### ISSUE TITLE
No such module 'EstimoteProximitySDK'

### ISSUE THREAD

**Issue by michaelcuneo** [Estimote/iOS-Proximity-SDK#32]
Multiple issues with new builds on XCode 10, targetting iOS 10.

Following the SDK Setup instructions for a .Podfile installation on iOS... for Swift, I get 

No such module 'EstimoteProximitySDK'... 

Following the SDK Setup instructions for a .Podfile installation on iOS... for Objective C, I get a valid compilation and run, but it segfaults on launch, with an unusual error.

The same issues occur across both attempts at Android installations... is there some kind of major problem with the iOS Proximity SDK right now, or is it my system environment?

**Comment by chwastek** [comment]
@michaelcuneo above all I would go with "standard" or close/restart/deep clean/delete derived data/etc. combo with Xcode and Mac OS. Very often it helps in such cases, no matter what is the origin.

What is this
> unusual error

?

And what exactly happens with Android SDK?
