### ISSUE TITLE
Estimote Analytics

### ISSUE THREAD

**Issue by rohitup** [Estimote/iOS-Proximity-SDK#34]
How to enable Estimote analytics in the proximity zone?

**Comment by chwastek** [comment]
Only analytics you could/can enable is through `EPXProximityObserverConfiguration` where you provide flag indicating if you want to share telemetry readings to Estimote Cloud (see [here](https://github.com/Estimote/iOS-Proximity-SDK/blob/38be2c8e32e2a6e66985115a96765077802ae685/EstimoteProximitySDK/EstimoteProximitySDK.framework/Headers/EPXProximityObserverConfiguration.h#L56)).
