### ISSUE TITLE
Fetching devices attached to provided tags failed!

### ISSUE THREAD

**Issue by nanli** [Estimote/iOS-Proximity-SDK#36]
I just started using the SDK, I am using the latest version (1.12.0) and I always have this problem when starting the App. By the way, I connect my iPhone to my Mac with cable and load the App from Xcode directly (I have no paid Apple development account, so I am using it on my own phone only). 

**_Fetching devices attached to provided tags failed!
When running offline, internet connection is required when starting the observer for the first time.
proximity observer error: Error Domain=EPXProximityObserverErrorDomain Code=1 "Fetching tags from Cloud failed." UserInfo={NSUnderlyingError=0x2822f8120 {Error Domain=EstimoteProximitySDK.PersistentTagsRepository.Error Code=2 "When running offline, internet connection is required when starting the observer for the first time."}, NSLocalizedDescription=Fetching tags from Cloud failed., NSLocalizedRecoverySuggestion=Make sure your cloud credentials are correct and you have a valid internet connection. See CloudCredentials for more.}_**

This looks like that it is reporting no internet connection. But I have internet connection, I am browsing the web at the same time.  and there is nothing blocking the internet. I also have set up tag names, and the tag names have more than 4 characters.  If you need my AppID to check what is going on. Here it is : dashboard-3y1

Please let me know what the problem might be.

**Comment by nanli** [comment]
Tried for some hours, and it suddenly worked ..... I don't even know the reason... This issue can be closed.

**Comment by jordansnyder** [comment]
I noticed that this happened when I tried to set up a zone for a tag that didn't exist. I fixed the tag in the web dashboard and instantly stopped getting this error. I think the real problem is the generic error message and IMO this should be re-opened to fix that.

**Comment by huynhpeter** [comment]
This is also happening to me and I'm not sure why. Where do you go to set the tags? I'm new to beacon technology, so any advice would help. Thanks!

**Comment by chwastek** [comment]
@jordansnyder noted and added to the backlog!
@huynhpeter https://github.com/Estimote/iOS-Proximity-SDK#setting-up-tags

**Comment by thewizster** [comment]
Receiving same error. I found that the tags are case sensitive. Made sure case matched and error is gone.
