### ISSUE TITLE
Get RSSI value

### ISSUE THREAD

**Issue by abhi17jas** [Estimote/iOS-Proximity-SDK#37]
How to get the RSSI value of detected beacon while using the iOS-Proximity-SDK?

**Comment by chwastek** [comment]
@abhi17jas unfortunately you cannot currently do that, as each zone is operating on `ProximityZoneContext` which consists of:
- beacon's identifier
- tag's name
- dictionary of attachments assigned to that beacon
Regards
@chwastek
