### ISSUE TITLE
[IOS] App rejected when upload release package on testflight

### ISSUE THREAD

**Issue by croustibat** [Estimote/iOS-Proximity-SDK#4]
Hello guys,

Just to let you know there's 2 issues when trying to upload the release package on itunesconnect (testFlight) :

1. EstimoteBluetoothScanning.framework The Info.plist file is missing the required key: CFBundleVersion. 
```
open info.plist in xcode and add CFBundleVersion (actually it is present but empty) 
```
2. Both executables for EstimoteBluetoothScanning.framework and EstimoteProximitySDK.framework contains unsupported architectures [x86_64, i386]
For this issue, use the command line
```
lipo -info EstimoteProximitySDK

lipo -remove x86_64 EstimoteProximitySDK -o EstimoteProximitySDK
lipo -remove i386 EstimoteProximitySDK -o EstimoteProximitySDK

lipo -remove x86_64 EstimoteBluetoothScanning -o EstimoteBluetoothScanning
lipo -remove i386 EstimoteBluetoothScanning -o EstimoteBluetoothScanning
```
So i manage to upload my binaries, but i though it could be helpful for others to know ;)

**Comment by airalex** [comment]
Hey @croustibat 

Thanks for sharing this! 

Issue 1: I'll add the missing key in the next release of EstimoteBluetoothScanning.

Issue 2: This is probably related to App Store rejecting builds with iOS simulator slices. How did you add Proximity SDK to your project – manually, with CocoaPods, or with Carthage?

**Comment by croustibat** [comment]
I added the Proximity SDK manually : General > Linked Framework and Libraries
