### ISSUE TITLE
Estimote Telemetry Bug

### ISSUE THREAD

**Issue by TouregoYew** [Estimote/iOS-Proximity-SDK#40]
Please refer to 
https://forums.estimote.com/t/how-to-use-estimote-telemetry/9664/6

> I now believe this a bug in the iOS Proximity SDK. If I read our code correctly, we’re waiting to collect 100 telemetry frames before sending them to Estimote Cloud. But, these need to be 100 frames from different beacons, which I believe is not the intended design

**Comment by chwastek** [comment]
@TouregoYew apologies for taking so long, but it's coming within next few days in version 1.5.0 ✌️

**Comment by chwastek** [comment]
fixed with version https://github.com/Estimote/iOS-Proximity-SDK/releases/tag/v1.4.1
