### ISSUE TITLE
[iOS] Could not find module 'EstimoteProximitySDK'

### ISSUE THREAD

**Issue by gelodgreat** [Estimote/iOS-Proximity-SDK#41]
Could not find module 'EstimoteProximitySDK' for architecture 'x86_64'; found: arm64, arm

XCode 10 beta 2

**Comment by rogerdalal** [comment]
Here we are again. Xcode 10.2 / Swift 5.0 officially out as of 3/25, and the EstimoteSDK isn't ready. Despite the above posted over a month ago.

**Comment by magnuskahr** [comment]
> Here we are again. Xcode 10.2 / Swift 5.0 officially out as of 3/25, and the EstimoteSDK isn't ready. Despite the above posted over a month ago.

I got the following mail from the supportteam today regarding swift 5 Xcode 10.2: 

> Hi Magnus,
> 
> Thanks for getting in touch!
> We'll be updating the SDK in the next few days to make it fully compatible with the latest Xcode and Swift. We should be ready this week, but keep an eye on the repo. :)
> 
> Best regards,
> 
> —
> Rafal 
> Customer Experience
> Estimote, Inc.

**Comment by rogerdalal** [comment]
Thank you @magnuskahr for the update. At least that's something.

**Comment by dewey4iv** [comment]
hey @magnuskahr -- I'm wondering if this is related to the same issue:

```dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/georgewheeler/Library/Developer/CoreSimulator/Devices/E1CC9BC6-E371-45B6-B766-251FEC25021F/data/Containers/Bundle/Application/4BF0219C-8E74-41E1-91AC-77252994A6C3/example.app/Frameworks/EstimoteProximitySDK.framework/EstimoteProximitySDK
  Reason: Incompatible library version: EstimoteProximitySDK requires version 1.0.0 or later, but libswiftCore.dylib provides version 0.0.0```

I am on the newest Xcode (10.2) but using the 4.2.0 Swift toolchain.

**Comment by magnuskahr** [comment]
@dewey4iv well I have **not** myself been able to make the SKD run in Xcode 10.2, no matter what toolchain. So I guess its related!

**Comment by rogerdalal** [comment]
Latest update (v1.3.1) resolves these issues on iOS 12.2 and Xcode 10.2. Thank you, Estimote.

**Comment by dewey4iv** [comment]
I wanted to explicitly state that this resolve my issues :). Thanks, Estimote!

**Comment by ReemaAH** [comment]
Hello, I'm facing the same issue here
swift version: 4.2 
and Xcode version 11.5 
how to solve that?
