### ISSUE TITLE
EsimoteProximitySDK: Module compiled with Swift 5.0 cannot be imported by the Swift 4.2.1 compiler

### ISSUE THREAD

**Issue by hstrey** [Estimote/iOS-Proximity-SDK#42]
I am using XCode 10.1 and I cannot get the ProximitySDK to work.  Using CocoaPods.

**Comment by hstrey** [comment]
solved problem by moving back to 1.2.0.  Could you please indicate in the code tree which Swift version is used? Swift 5 for 1.3.x on.

**Comment by chwastek** [comment]
@hstrey please use SDK starting with version 1.3.x
here is the commit that introduced the support for Swift 5 -> https://github.com/Estimote/iOS-Proximity-SDK/commit/30bde051d49f20c452e75f4c20f4716e3998dee2

We try to include any important notes (like supporting Swift 5) in [changelog](https://github.com/Estimote/iOS-Proximity-SDK/blob/master/CHANGELOG.md)

Hope it helps
