### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by karthironald** [Estimote/iOS-Proximity-SDK#46]
Hi,

I'm using latest EstimoteProximitySDK version 1.4.1 and Xcode 11 beta (11M336w). When I build my project I'm getting **Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler** error. Can anyone please help? When can we expect Swift 5.1 update? Please let me know if i miss anything. 

Thanks!

**Comment by karthironald** [comment]
Any updates in this?

**Comment by dandreikiv** [comment]
I have the same issue.

**Comment by daningamells** [comment]
Same issue :-(

**Comment by heypiotr** [comment]
Thanks for your reports all, and sorry for the long wait! ^_^

We should have an update for Swift 5.1 very soon, hopefully by the end of this week.

The good news is, with Module Stability in Swift 5.1, this should be the last time you see an issue like this. Module Stability means that going forward, you can take a Swift 5.1 library (e.g., the next version of the Proximity SDK), and use it with any future Swift compiler (:

**Comment by karthironald** [comment]
Looking for updated version soon! Thanks for the update.

**Comment by heypiotr** [comment]
`1.5.0-beta1` is now available, in this repo and on CocoaPods, let us know if it works for you.

The final 1.5.0 will come after Xcode 11 releases as stable.

**Comment by karthironald** [comment]
Will check and update you! Thanks!

**Comment by novinfard** [comment]
I used the latest build and now it works with Xcode 11, not with Xcode 10 now! The same error is shown. I cleared my build to be sure about everything.
