### ISSUE TITLE
Updating proximityObserver

### ISSUE THREAD

**Issue by jayychang** [Estimote/iOS-Proximity-SDK#51]
Wasn't able to find a solid answer for updating for `proximityObserver`, but does calling a `proximityObserver.startObserving()` with a new payload replaces all previous observables?

**Comment by chwastek** [comment]
I would be cautious when using `observables` here - iOS SDK for Proximity is not reactive. But if you're asking if calling observing new set of zones will replace old ones - then yes, it will.
