### ISSUE TITLE
Beacon is not register in iOS 13

### ISSUE THREAD

**Issue by Mohamedadin** [Estimote/iOS-Proximity-SDK#52]
After upgrading Estimote libraries using Cocoapods as follows:
```
pod 'EstimoteProximitySDK', '1.5.0'
pod 'EstimoteBluetoothScanning' , '1.0.7'
```
We can't register beacon in iOS 13.1.3 device.

However the live build on App Store is working fine with  iOS 13 and the following pods versions
```
pod 'EstimoteProximitySDK', '1.4.1'
pod 'EstimoteBluetoothScanning' , '1.0.5'
```
Quick response is needed :)

**Comment by chwastek** [comment]
Formatted a little your post (hopefully it is how you intended?) - can you clarify what do you mean by _register_? Do you mean _detect_?

> btw there is newer version of iOS so probably it would be good to test it on the latest version anyway

**Comment by Mohamedadin** [comment]
Thank you for your reply.
I mean scanning and connecting the beacon. It takes too much time without response.
I used the following:
`func deviceManager(_: ESTDeviceManager, didDiscover devices: [ESTDevice]) {
        let nextGenBeacons = devices
        let beaconsWithNormalizedRSSI = nextGenBeacons.map { ($0, normalizedRSSIForBeaconWithIdentifier($0.identifier, RSSI: $0.rssi)) }.filter { $0.1 != nil && $0.1! >= 0 }
        let nearestBeacon = beaconsWithNormalizedRSSI.max { $0.1! < $1.1! }?.0

        if let nearestBeacon = nearestBeacon as? ESTDeviceLocationBeacon {
            delegate.immediateBeaconDetector(self, didDiscoverBeacon: nearestBeacon)
        }
    }`

**Comment by chwastek** [comment]
Estimote Proximity SDK is not for connecting or detecting beacons, but for detecting tagged zones (which are in fact a group of beacons with a specific tag attached to them in the Cloud). 

If you need to do so [detect & connect] (as I can see you're trying to from the snippet you provided) all you would need is [Estimote Fleet Management SDK](https://github.com/Estimote/iOS-Fleet-Management-SDK). So please file an issue there (don;t forget to test newest iOS stack as well) to avoid mess in issues here. In the meantime I'll try to investigate if Fleet Management is working or not, and will reply to your issue regarding Fleet Management (👉 [here](https://github.com/Estimote/iOS-Fleet-Management-SDK/issues))
