### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.2 compiler:

### ISSUE THREAD

**Issue by SavioVaz99** [Estimote/iOS-Proximity-SDK#55]
Using "import EstimoteProximitySDK" in my code gives me 

"Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.2 compiler: "

Using Xcode 11.2.1

**Comment by chwastek** [comment]
@SavioVaz99 we'll fix it with the next release, this week

**Comment by chwastek** [comment]
@SavioVaz99 please checkout from Cocoaopds, should be in few minutes available (https://github.com/Estimote/iOS-Proximity-SDK/releases/tag/v1.6.0)
