### ISSUE TITLE
0.11.0 not working in background. 

### ISSUE THREAD

**Issue by ivopisarovic** [Estimote/iOS-Proximity-SDK#6]
After updating from 0.10.0 to 0.11.0 events are coming only when the app is in foreground. When the app is in background, _onEnterAction_, _onExitAction_ and _onChangeAction_ is not called. No error is logged. Are any changes necessary in the code? I used the same code as for 0.10.0. With the version 0.10.0 it was working fine both in the foreground and in the background. 

```
let cloudCredentials = EPXCloudCredentials(appID: Constants.sync.estimote.appId, appToken: Constants.sync.estimote.appToken)
        self.proximityObserver = EPXProximityObserver(
            credentials: cloudCredentials,
            errorBlock: { error in
                warning("Estimote Proximity observer error: \(error)")
})

let zone = EPXProximityZone(range: .far, attachmentKey: "...", attachmentValue: "...")
zone.onChangeAction = didChangeZone
self.zone = zone
observer.startObserving([zone])
```

Xcode 9.2, Swift 4, iOS 11.2.5. 

Thanks for response.

**Comment by airalex** [comment]
Hey @ivopisarovic

I've verified that this is caused by a bug in the SDK, you can expect a bug fixing release soon. If you really need to work with observing proximity zones in the background, please use v0.10.0 until the fixes ship.

Thanks!

**Comment by airalex** [comment]
[v0.11.1](https://github.com/Estimote/iOS-Proximity-SDK/releases/tag/v0.11.1) contains fixes for this issue, so the callbacks should be called normally now. We must have missed this when preparing v0.11.0 build, thanks again for reporting, @ivopisarovic!
