### ISSUE TITLE
Proximity library does not compile with latest Xcode (13.2.1)

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [Estimote/iOS-Proximity-SDK#64]
Version 13.2.1 (13C100)

Upon attempting to build a brand new empty template downloaded from the portal, I'm receiving the following non-start compile error.

Module compiled with Swift 5.2 cannot be imported by the Swift 5.5.2 compiler.

Swift 5.5 is a minimum requirement for me, any chance that your library will get an update to SPM using XCFrameworks and a support for newer Swift language level?

**Comment by Touutae-lab** [comment]
I have an issue too
module compiled with Swift 5.1 cannot be imported by the Swift 5.5.2 compiler

**Comment by SwiftNativeDeveloper** [comment]
Thanks @djhayden!
