### ISSUE TITLE
Cocoapods issues

### ISSUE THREAD

**Issue by megataps** [Estimote/iOS-Proximity-SDK#8]
I got a error when add this SDK to project:

[!] CocoaPods could not find compatible versions for pod "EstimoteProximitySDK":
  In Podfile:
    EstimoteProximitySDK

Specs satisfying the `EstimoteProximitySDK` dependency were found, but they required a higher minimum deployment target.

**Comment by Trupti15** [comment]
> platform :ios, '10.0'

Thank you, Sir. It works.
